const $ = {
  gameOver: document.getElementById('game-over'),
  progress: document.getElementById('progress'),
  progressBar: document.getElementById('progress-bar'),
  progressValue: document.getElementById('progress-value'),
  panels: document.getElementById('panels'),
  captainsLog: document.getElementById('captains-log'),
  captainsLogClose: document.getElementById('captains-log-close'),
  version: document.getElementById('version'),
  fuelAutoProducers: document.getElementById('fuel-auto-producers'),
  fuelAutoProducersAdd: document.getElementById('fuel-auto-producers-add'),
  fuelAutoProducersRemove: document.getElementById('fuel-auto-producers-remove'),
  fuelAutoProducersWrapper: document.getElementById('fuel-auto-producers-wrapper'),
  fuelAutoProducersCost: document.getElementById('fuel-auto-producers-cost'),
  fuelPercentage: document.getElementById('fuel-percentage'),
  fuelProduceButton: document.getElementById('fuel-produce'),
  fuelTotal: document.getElementById('fuel-total'),
  fuelCapacity: document.getElementById('fuel-capacity'),
  fuelCapacityGauge: document.getElementById('fuel-capacity-gauge'),
  navigationIngnition: document.getElementById('navigation-ignition'),
  navigationConsumption: document.getElementById('navigation-consumption'),
  navigationSpeed: document.getElementById('navigation-speed'),
  navigationDistance: document.getElementById('navigation-distance'),
  navigationThurstersBasic: document.getElementById('navigation-thursters-basic'),
  navigationThurstersSuper: document.getElementById('navigation-thursters-super'),
  navigationThurstersMega: document.getElementById('navigation-thursters-mega'),
  saveGame: document.getElementById('save-game'),
  resetGame: document.getElementById('reset-game'),
};

export default $;
